### ISSUE TITLE
Hero sectiondagi background-imageni to'liq olish kerak figmadan.

### ISSUE THREAD

**Issue by akramjonnuriddinov** [Muhammadumar2002/apple-watch#1]
![image](https://user-images.githubusercontent.com/99048411/161411497-02fbff11-6e0a-48cf-9dc1-ade9d7ef18da.png)
Buyerda rasm to'liq olinmagan. 
![image](https://user-images.githubusercontent.com/99048411/161411527-ac452ddb-077f-409f-93ca-fe68072f173e.png)
-- Shu holatda rasmni chaproqqa olib keyin yuklab olish mumkin.

**Comment by Muhammadumar2002** [comment]
![image](https://user-images.githubusercontent.com/99244994/161479292-a5b057eb-553e-481b-a60a-949b8322303d.png)
-- To'g'rilandi
